---
- name: Create apt keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Add apt signing key
  ansible.builtin.apt_key:
    id: "{{ nextdns_apt_key_fingerprint }}"
    url: "{{ nextdns_apt_key_url }}"
    keyring: /etc/apt/keyrings/nextdns.gpg
    state: present

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/etc/apt/keyrings/nextdns.gpg]
      {{ nextdns_apt_repo }}
    filename: nextdns
    update_cache: true
    state: present

- name: "Add system group"
  ansible.builtin.group:
    name: "{{ nextdns_group }}"
    system: true
    state: present
  when: nextdns_manage_user

- name: "Add system user"
  ansible.builtin.user:
    name: "{{ nextdns_user }}"
    group: "{{ nextdns_group }}"
    system: true
    shell: /usr/sbin/nologin
    createhome: false
    state: present
  when: nextdns_manage_user

- name: Install nextdns
  ansible.builtin.apt:
    pkg: "nextdns"
    install_recommends: false
    state: present

- name: Configure /etc/nextdns.conf
  ansible.builtin.template:
    src: "nextdns.conf"
    dest: "/etc/nextdns.conf"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
  notify: "restart nextdns"
  when: nextdns_config != ""

- name: "Add systemd service"
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/nextdns.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: "restart nextdns"

- name: "Start and enable systemd service"
  ansible.builtin.systemd:
    name: "nextdns.service"
    daemon_reload: true
    enabled: true
    state: started
