---
- name: Install dependencies
  ansible.builtin.apt:
    pkg:
      - "python3-debian"

- name: Remove old nextdns apt configuration
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/apt/sources.list.d/nextdns.list"

- name: Add nextdns apt repository
  ansible.builtin.deb822_repository:
    name: nextdns
    uris: "{{ nextdns_apt_repo_url }}"
    suites: "{{ nextdns_apt_repo_suite }}"
    components: "{{ nextdns_apt_repo_component }}"
    signed_by: "{{ nextdns_apt_repo_gpg_key }}"
    state: present
  register: _apt_repo

- name: "Add system group"
  ansible.builtin.group:
    name: "{{ nextdns_group }}"
    system: true
    state: present
  when: nextdns_manage_user

- name: "Add system user"
  ansible.builtin.user:
    name: "{{ nextdns_user }}"
    group: "{{ nextdns_group }}"
    system: true
    shell: /usr/sbin/nologin
    createhome: false
    state: present
  when: nextdns_manage_user

- name: Install nextdns
  ansible.builtin.apt:
    pkg: "nextdns"
    install_recommends: false
    update_cache: "{{ true if _apt_repo is changed else false }}"
    state: present

- name: Configure /etc/nextdns.conf
  ansible.builtin.template:
    src: "nextdns.conf"
    dest: "/etc/nextdns.conf"
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
  notify: "restart nextdns"
  when: nextdns_config != ""

- name: "Add systemd service"
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/nextdns.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  register: _unit_file
  notify: "restart nextdns"

- name: "Start and enable systemd service"
  ansible.builtin.systemd:
    name: "nextdns.service"
    daemon_reload: >-
      {{ true if _unit_file is changed else false }}
    enabled: true
    state: started
